data-path="/home/node4/besuNode4/data"
# This is the datapath where the blockchain data will be stored
network-id=1337
genesis-file="/home/node4/besuNode4/Clique-Network/cliqueGenesis.json"
# Network
bootnodes=[
    "enode://675c010c5290a38c7ecd28aaba6a05a562e64955c39dc97368639ee3672ef08d0f864143595050b7d0e91ea95f5ab70ff331b1cf0a9aeaa9efca366a6ddabb39@127.0.0.1:30303",
]
# allows for the bootnodes to discover each other as they start up. In
# this example, there are three bootnodes stipulated for this network

#P2P
p2p-host="127.0.0.1"
p2p-interface="0.0.0.0"
p2p-port=30303
discovery-enabled=true
remote-connections-limit-enabled=true
remote-connections-max-percentage=60
random-peer-priority-enabled=false
host-allowlist=["*"]
engine-host-allowlist=["*"]
engine-rpc-enabled=true
#engine-jwt-disabled=true
#max-peers=42
# SYNC
#sync-mode="FAST"
#fast-sync-min-peers=1

# Database
data-storage-format="FOREST"

max-peers=42
# The maximum number of peer to peer connections this network can

# JSON-RPC
rpc-http-host="127.0.0.1"
rpc-http-port=8545
rpc-ws-enabled=true
rpc-ws-host="127.0.0.1"
rpc-ws-port=9001
rpc-http-api=["ETH","NET","WEB3","CLIQUE","ADMIN"]
rpc-http-enabled=true
rpc-http-cors-origins=["*"]
engine-rpc-port = 8551
# GRAPHQL-RPC
graphql-http-enabled=true
graphql-http-host="127.0.0.1"
graphql-http-port=10001
graphql-http-cors-origins=["*"]
# Transaction Pool
tx-pool="layered"
tx-pool-price-bump=13
tx-pool-blob-price-bump=100
rpc-tx-feecap=200000
#strict-tx-replay-protection-enabled=true
tx-pool-no-local-priority=false
tx-pool-priority-senders=["0xfe3b557e8fb62b89f4916b721be55ceb828dbd73","0x627306090abaB3A6e1400e9345bC60c78a8BEf57"]
tx-pool-enable-save-restore=true
tx-pool-save-file="txpool.dump"
## Layered
tx-pool-layer-max-capacity=12345678
tx-pool-max-prioritized=9876
tx-pool-max-prioritized-by-type=["BLOB=10","FRONTIER=100"]
tx-pool-max-future-by-sender=321
## Legacy/Sequenced
#tx-pool-retention-hours=999
#tx-pool-max-size=1234
#tx-pool-limit-by-account-percentage=0.017
tx-pool-min-gas-price=1000

miner-enabled=true
# This option enables mining when the node is started. The type of
# consensus mechanism will be stipulated in the genesis file

miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
# miner-coinbase provides the account to which mining rewards will be
# paid for this blockchain

#TLS-P2P
#Xp2p-tls-enabled=true
#Xp2p-tls-keystore-type="JKS"
#Xp2p-tls-keystore-file="/home/node2/besu/cert/node2-keystore.jks"
#Xp2p-tls-keystore-password-file="/home/node2/besu/cert/password.txt"
#Xp2p-tls-crl-file="/home/kyo/besu/cert/Node2/crl.pem"
#Xp2p-tls-truststore-type="JKS"
#Xp2p-tls-truststore-file="/home/node2/besu/cert/node2-truststore.jks"
#Xp2p-tls-truststore-password-file="/home/node2/besu/cert/password.txt"
